"""Strict, auditable building blocks for AI-guided district search."""

from .ai import (
    AIResult,
    GuidedAIError,
    ModelCallMetadata,
    OllamaTransport,
    RequestsOllamaTransport,
    StructuredOllamaClient,
    evaluate_search_results,
    plan_search,
    revise_search_plan,
    summarize_guided_search,
)
from .example_content import (
    ExampleContent,
    ExampleContentError,
    ExampleContentFetcher,
    ExampleContentTooLarge,
    ExampleHTTPError,
    PinnedUrllib3Transport,
    UnsafeExampleURLError,
    UnsupportedExampleContent,
    fetch_example_content,
)
from .models import (
    MODE_POLICIES,
    EvaluationCriteria,
    GuidedSummary,
    ModePolicy,
    PlanRevision,
    ResourcePolicy,
    SchemaValidationError,
    SearchConcept,
    SearchEvaluation,
    SearchPlan,
    SearchQuery,
    StopPolicy,
    mode_policy,
)
from .resources import (
    AdaptiveResourceController,
    NvidiaTelemetry,
    ResourceAdjustment,
    ResourceSnapshot,
    ThreadSafeDelayController,
    collect_resource_snapshot,
    parse_retry_after,
    read_nvidia_telemetry,
)


__all__ = [
    "AIResult",
    "AdaptiveResourceController",
    "EvaluationCriteria",
    "ExampleContent",
    "ExampleContentError",
    "ExampleContentFetcher",
    "ExampleContentTooLarge",
    "ExampleHTTPError",
    "GuidedAIError",
    "GuidedSummary",
    "MODE_POLICIES",
    "ModePolicy",
    "ModelCallMetadata",
    "NvidiaTelemetry",
    "OllamaTransport",
    "PinnedUrllib3Transport",
    "PlanRevision",
    "RequestsOllamaTransport",
    "ResourceAdjustment",
    "ResourcePolicy",
    "ResourceSnapshot",
    "SchemaValidationError",
    "SearchConcept",
    "SearchEvaluation",
    "SearchPlan",
    "SearchQuery",
    "StopPolicy",
    "StructuredOllamaClient",
    "ThreadSafeDelayController",
    "UnsafeExampleURLError",
    "UnsupportedExampleContent",
    "collect_resource_snapshot",
    "evaluate_search_results",
    "fetch_example_content",
    "mode_policy",
    "parse_retry_after",
    "plan_search",
    "read_nvidia_telemetry",
    "revise_search_plan",
    "summarize_guided_search",
]
